apiVersion: v1
kind: Pod
metadata:
  name: gae
spec:
  securityContext:
    runAsUser: 270999
    runAsGroup: 1132
  restartPolicy: Never
  containers:
    - name: gae-pod
      #image: docker.io/pytorch/pytorch:2.5.1-cuda12.4-cudnn9-runtime
      image: ghcr.io/stmorse/torch-gen:latest
      resources:
        requests:
          memory: '64Gi'
          nvidia.com/gpu: '1'
          cpu: '16'
        limits:
          memory: '64Gi'
          nvidia.com/gpu: '1'
          cpu: '16'
      command: ['/bin/sh']
      args:
        - '-c'
        - |
          echo "Running container..."   
          cd /sciclone/home/stmorse/classes/nndl/project
          python -u train.py \
            --subfolder charged --suffix _charged5 \
            --save-folder logs/gae --epochs 50 \
            --encoder cnn \
            > logs/gae/gae_25-04-29_2.log 2>&1
          # sleep infinity
      volumeMounts:
        - name: home
          mountPath: /sciclone/home/stmorse
  volumes:
    - name: home
      nfs:
        server: 128.239.56.166
        path: /sciclone/home/stmorse